apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-telemetry-dashboard
  namespace: opcapp
  labels:
    app: dashboard
spec:
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      serviceAccountName: opcua-telemetry-dashboard
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: opcua-telemetry-dashboard
          image: "grafana/grafana:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: dashboard
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          volumeMounts:
            - name: workload-token
              mountPath: /var/run/secrets/tokens
            - name: zta-svids
              mountPath: /var/run/secrets/svids
          resources: {}
      imagePullSecrets:
        - name: hestia-acr-secret
      volumes:
        - name: zta-svids
          emptyDir: {}
        - name: workload-token
          projected:
            sources:
              - serviceAccountToken:
                  path: workload
                  expirationSeconds: 7200
                  audience: zta-agent
