apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.serviceInstanceName }}-{{ .Values.global.sysServices.ztaController}}
  namespace: {{ .Values.global.serviceInstanceName }}-system
data:
  ztaadmission-cfg.toml: |
    zta_agent_workload_api_port = {{ .Values.global.ztaAgentWorkloadApiPort }}
    zta_ctrld_api_port = {{ .Values.webHookPort }}
    svid_dir_path = "{{ tpl .Values.global.svidDirPath . }}"
    zta_proxy_image = "{{ tpl .Values.global.sources.containerRegistry . }}/{{ tpl .Values.global.sysServices.ztaProxy . }}:{{ tpl .Values.global.sources.images.tag .}}"
    zta_proxy_image_pull_policy = "Always"
    zta_proxy_image_pull_secret =  "hestia-acr-secret"
    workload_token_path = "/var/run/secrets/tokens"
