apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl .Values.global.serviceInstanceName . }}-{{ .Values.global.sysServices.ztaController}}
  namespace: {{ .Values.global.serviceInstanceName }}-system
  