apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.sysServices.ztaController }}
  namespace: {{ .Values.global.serviceInstanceName }}-system
spec:
  type: ClusterIP
  ports:
    - name: admission
      port: {{ .Values.svcPort }}
      targetPort: {{ .Values.webHookPort }}
      protocol: TCP
  selector:
    app: {{ .Values.global.serviceInstanceName }}-{{ .Values.global.sysServices.ztaController}}
