apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-server
  namespace: opcapp
  labels:
    app: opcua
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: opcua-server
      containers:
        - name: opcua-server
          image: "crhestiamp.azurecr.io/opcplcserver:beta"
          imagePullPolicy: IfNotPresent
          command:
            [
              "/bin/bash",
              "-c",
              "./opcplc --pn=50000 --at X509Store --autoaccept --sph --sn=5 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint --gn=5",
            ]
          ports:
            - name: opcplc
              containerPort: 50000
              protocol: TCP
          volumeMounts:
            - name: workload-token
              mountPath: /var/run/secrets/tokens
            - name: zta-svids
              mountPath: /var/run/secrets/svids
          resources: {}
      imagePullSecrets:
        - name: hestia-acr-secret
      volumes:
        - name: zta-svids
          emptyDir: {}
        - name: workload-token
          projected:
            sources:
              - serviceAccountToken:
                  path: workload
                  expirationSeconds: 7200
                  audience: zta-agent
