apiVersion: v1
kind: Service
metadata:
  name: opcua-historian
  namespace: opcapp
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: tsdb
