apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-capacity-job
  namespace: {{ .Values.global.serviceInstanceName }}-system
spec:
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ tpl .Values.global.serviceInstanceName . }}-{{ .Values.global.sysServices.capacityServiceEdge}}
          containers:
          - name: cluster-capacity-job
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - curl
            - http://cluster-capacity-edge/api/v1/clusters/capacity
            volumeMounts:
            - name: workload-token
              mountPath: /var/run/secrets/tokens
            - name: zta-svids
              mountPath: /var/run/secrets/svids
            - name: config
              mountPath: /usr/local/hestia
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: cluster-capacity-edge
          - name: zta-svids
            emptyDir: {}
          - name: workload-token
            projected:
              sources:
              - serviceAccountToken:
                  path: workload
                  expirationSeconds: {{ .Values.global.serviceAccountTokenExpirationSeconds }}
                  audience: {{ .Values.global.sysServices.ztaAgent }}