apiVersion: v1
kind: Service
metadata:
  name: cluster-capacity-edge
  namespace: {{ .Values.global.serviceInstanceName }}-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: cluster-capacity-edge