# Source: edge-capacity-service/charts/edge-capacity-svc/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hestia-cluster-capacity-edge
  namespace: hestia-system
---
# Source: edge-capacity-service/charts/edge-capacity-svc/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-capacity-edge
  namespace: hestia-system
data:
  cluster-capacity.env: |
    # Application settings
    APP_HOST="0.0.0.0"
    APP_PORT=3000
    APP_READ_TIMEOUT=30
    APP_DEBUG=false

    # Azure AD settings
    SUBSCRIPTION_ID="b0c2f310-88be-48d1-95d0-7cc9947687b5"
    AZURE_ARC_NAMESPACE="azure-arc"
    AZURE_ARC_CONFIG_MAP_NAME="azure-clusterconfig"
    CLUSTER_CAPACITY_CLOUD_API_URL="http://20.75.227.90/api/v1/clusters/capacity"
---
# Source: edge-capacity-service/charts/edge-capacity-svc/templates/clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hestia-cluster-capacity-edge-cluster-role
  namespace: hestia-system
rules:
- apiGroups:
  - ""
  - metrics.k8s.io
  resources:
  - nodes
  - configmaps
  verbs:
  - get
  - list
---
# Source: edge-capacity-service/charts/edge-capacity-svc/templates/clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hestia-cluster-capacity-edge-cluster-role-binding
  namespace: hestia-system
subjects:
- kind: ServiceAccount
  name: hestia-cluster-capacity-edge
  namespace: hestia-system
roleRef:
  kind: ClusterRole
  name: hestia-cluster-capacity-edge-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: edge-capacity-service/charts/edge-capacity-svc/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cluster-capacity-edge
  namespace: hestia-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: cluster-capacity-edge
---
# Source: edge-capacity-service/charts/edge-capacity-svc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-capacity-edge
  namespace: hestia-system
spec:
  selector:
    matchLabels:
      app: cluster-capacity-edge
  template:
    metadata:
      labels:
        app: cluster-capacity-edge
    spec:
      serviceAccountName: hestia-cluster-capacity-edge
      containers:
      - name: cluster-capacity-edge
        image: privsaasv1intacr.azurecr.io/cluster-capacity-edge:1.0.0
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        volumeMounts:
        - name: workload-token
          mountPath: /var/run/secrets/tokens
        - name: zta-svids
          mountPath: /var/run/secrets/svids
        - name: config
          mountPath: /usr/local/hestia
        resources: {}
      imagePullSecrets:
        - name: hestia-acr-secret
      volumes:
        - name: config
          configMap:
            name: cluster-capacity-edge
        - name: zta-svids
          emptyDir: {}
        - name: workload-token
          projected:
            sources:
            - serviceAccountToken:
                path: workload
                expirationSeconds: 
                audience: zta-agent
---
# Source: edge-capacity-service/charts/edge-capacity-svc/templates/cronJob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-capacity-job
  namespace: hestia-system
spec:
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: hestia-cluster-capacity-edge
          containers:
          - name: cluster-capacity-job
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - curl
            - http://cluster-capacity-edge/api/v1/clusters/capacity
            volumeMounts:
            - name: workload-token
              mountPath: /var/run/secrets/tokens
            - name: zta-svids
              mountPath: /var/run/secrets/svids
            - name: config
              mountPath: /usr/local/hestia
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: cluster-capacity-edge
          - name: zta-svids
            emptyDir: {}
          - name: workload-token
            projected:
              sources:
              - serviceAccountToken:
                  path: workload
                  expirationSeconds: 
                  audience: zta-agent

