apiVersion: v1
kind: Pod
metadata:
  labels:
    app: contoso-workload
  name: contoso-workload
spec:
  serviceAccountName: contoso-workload
  containers:
  - image: docker.io/library/nginx:latest
    imagePullPolicy: Always
    name: contoso-workload-rg
    resources: {}
    volumeMounts:
    - name: workload-token
      mountPath: /var/run/secrets/tokens
    - name: zta-svids
      mountPath: /var/run/secrets/svids
  volumes:
  - name: zta-svids
    emptyDir: {}
  - name: workload-token
    projected:
      sources:
      - serviceAccountToken:
          path: workload
          expirationSeconds: 7200
          audience: zta-agent
