apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.serviceInstanceName }}-{{ .Values.global.sysServices.ztaServer }}
  namespace: {{ .Values.global.serviceInstanceName }}-system
data:
  ztaserver-cfg.toml: |
    trust_domain = {{ .Values.global.trustDomainDnsName |quote }}
    is_spiffe_root = {{ .Values.isRootZtaServer }}
    token_audience = {{ .Values.global.sysServices.ztaServer |quote }}
    adminapi_bind_address = "0.0.0.0"
    adminapi_bind_port = {{ .Values.global.ztaServerAdminApiPort }}
    svidapi_bind_address = "0.0.0.0"
    svidapi_bind_port = {{ .Values.global.ztaServerSvidApiPort }}
    svid_ttl_hr = {{ .Values.svidTTLHours }}

    [signer_cert_cfg]
    signer_cert_ttl_hr = {{ .Values.selfSign.signerTTLHours }}
    country = "{{ tpl .Values.selfSign.country . }}"
    org = "{{ tpl .Values.selfSign.org . }}"
    common_name = {{ .Values.global.trustDomainDnsName |quote }}
    alg = "{{ tpl .Values.selfSign.alg . }}"
    rsa_key_size = "{{ tpl .Values.selfSign.keySize . }}"

    [system_config]
    instance_name = {{ .Values.global.serviceInstanceName |quote }}
    zta_services = [
        {{ .Values.global.sysServices.ztaAgent |quote }},
        {{ .Values.global.sysServices.ztaController |quote }},
        {{ .Values.global.sysServices.ztaServer |quote }}
    ]
    management_services = [
        {{ .Values.global.sysServices.controlPanel |quote }},
        {{ .Values.global.sysServices.clusterRegistry |quote }},
        {{ .Values.global.sysServices.fleetRegistry |quote }},
        {{ .Values.global.sysServices.workloadService |quote }},
    ]
    control_services = [
        {{ .Values.global.sysServices.bootstrapperService |quote }},
        {{ .Values.global.sysServices.capacityServiceCloud |quote }},
        {{ .Values.global.sysServices.deploymentService |quote }},
        {{ .Values.global.sysServices.deploymentPlanService |quote }},
        {{ .Values.global.sysServices.workloadSchedService |quote }},
    ]
    edge_services = [
        {{ .Values.global.sysServices.capacityServiceEdge |quote }},
    ]