apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceInstanceName }}-{{ .Values.global.sysServices.ztaServer }}
  namespace: {{ .Values.global.serviceInstanceName }}-system
  